[build]
  publish = "DOC-20260830-WA0017"

[[redirects]]
  from = "/"
  to = "/legacylock_landing_page.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
